### ISSUE TITLE
Ali - problem

### ISSUE THREAD

**Issue by slonskipotato** [longnull/GiveawayCompanion#17]
Hi, 
This issue is not related to Giveaway Companion repository,
but I want to ask you about Ali Address Randomizer. 
Not able to find other contact to you.
I had used your script since March, now using updated script but till tampermonkey not longer working on Chrome, I moved on Firefox.
But I have one problem on this browser: On City drop menu field I can't select any city.  
You can check on video. 

https://youtu.be/2-gKaXcxZxE

**Comment by longnull** [comment]
Hi. Yes, there is such a problem. AliExpress suddenly updated the old form (which appears because of the script, it doesn't work with the new form) and broke the field for selecting the city, you can't even select manually. So it's a problem on the AliExpress side, not in the script.

By the way, you can leave comments [here](https://gist.github.com/longnull/7bb9f946f3bba27a7d1df272291eef9f).
